on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: docker.io
  IMAGE_NAME: paulnorton311/gha
  REF_TAG: ${{ github.event.pull_request.head.sha || github.event.after }}
  PUSH_TAG: latest

jobs:
  build-push-compare:

    permissions:
      pull-requests: write
    
    runs-on: ubuntu-latest
    name: Docker Scout Compare

    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2.5.0
        with:
          driver-opts: |
            image=moby/buildkit

      - uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: paulnorton311
          password: ${{ secrets.DOCKER_PAT }}

      - uses: docker/build-push-action@v5
        if: ${{ github.event_name == 'pull_request' }}
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.REF_TAG }}

      - uses: docker/scout-action@v1.2.2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          command: compare
          organization: paulnorton311
          image: ${{ env.IMAGE_NAME }}:${{ env.REF_TAG }}
          to: ${{ env.IMAGE_NAME }}:${{ env.PUSH_TAG }}
          exit-on: policy,vulnerability

      - uses: docker/build-push-action@v5
        if: ${{ github.event_name != 'pull_request' }}
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.PUSH_TAG }}
          provenance: true
          sbom: true
